name: chess
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.4.1
  device_preview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/Chess_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo/logo_foreground.png"

  # dart run flutter_launcher_icons:main

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#272727"
  image: assets/logo/Chess_logo.png

  android_12:
    color: "#FFFFFF"
    color_dark: "#272727"
    image: assets/logo/Chess_logo.png

  web: false

  # dart run flutter_native_splash:create --path=pubspec.yaml
  # dart run flutter_native_splash:remove

flutter:
  uses-material-design: true

  assets:
    - assets/Images/
    - assets/Images/black/
    - assets/Images/white/
    - assets/logo/
