# This is an updated version of the previous code that fixes the issues

name: Deploy Live Preview to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the code from master
      - name: Checkout code from master
        uses: actions/checkout@v3
        with:
          ref: master

      # Step 2: Fetch and switch to live_preview branch and merge master
      - name: Switch to live_preview branch and merge master
        run: |
          git config --global user.email "khandelwalharshit431@gmail.com"
          git config --global user.name "Harshit2756"
          
          # Fetch the remote branches, including live_preview
          git fetch origin

          # Checkout the live_preview branch from remote
          git checkout live_preview

          # Merge master into live_preview
          git merge master

          # Push the merged changes back to the live_preview branch
          git push origin live_preview

      # Step 3: Replace main.dart with Device Preview code
      - name: Replace main.dart with Device Preview code
        run: |
          cat > lib/main.dart << 'EOF'
          import 'package:chess/gameboard.dart';
          import 'package:chess/values/colors.dart';
          import 'package:device_preview/device_preview.dart';
          import 'package:device_preview_screenshot/device_preview_screenshot.dart';
          import 'package:flutter/material.dart';

          Future<void> main() async {
            runApp(
              DevicePreview(
                backgroundColor: backgroundColor,
                tools: const [
                  DeviceSection(
                    frameVisibility: false,
                    orientation: false,
                  ),
                  SystemSection(
                    locale: false,
                    theme: true,
                  ),
                  DevicePreviewScreenshot(),
                  SettingsSection(),
                ],
                devices: [
                  Devices.android.samsungGalaxyA50,
                  Devices.android.samsungGalaxyNote20,
                  Devices.android.samsungGalaxyS20,
                  Devices.android.samsungGalaxyNote20Ultra,
                  Devices.android.onePlus8Pro,
                  Devices.android.sonyXperia1II,
                  Devices.ios.iPhoneSE,
                  Devices.ios.iPhone12,
                  Devices.ios.iPhone12Mini,
                  Devices.ios.iPhone12ProMax,
                  Devices.ios.iPhone13,
                  Devices.ios.iPhone13ProMax,
                  Devices.ios.iPhone13Mini,
                  Devices.ios.iPhoneSE,
                ],
                enabled: true,
                builder: (context) => const MyApp(),
              ),
            );
          }

          class MyApp extends StatelessWidget {
            const MyApp({super.key});

            @override
            Widget build(BuildContext context) {
              return MaterialApp(
                title: 'Chess',
                debugShowCheckedModeBanner: false,
                locale: DevicePreview.locale(context),
                builder: DevicePreview.appBuilder,
                home: const GameBoard(),
              );
            }
          }
          EOF

      # Step 4: Set up Flutter environment
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"

      # Step 5: Install Flutter dependencies
      - name: Install Flutter dependencies
        run: flutter pub get

      # Step 6: Build Flutter web app
      - name: Build Flutter for web
        run: flutter build web --release --web-renderer canvaskit

      # Step 7: Deploy to GitHub Pages using the docs folder
      - name: Deploy to GitHub Pages
        run: |
          rm -rf docs
          mv build/web docs
          git add docs
          git commit -m "Deploy live preview build to GitHub Pages"
          git push origin live_preview
